# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c848c16224e9c74d3a0dbd9fd133ba4a2f47f48699486960bd1280aceae7ed002e3a589799248a3f82aa629024cecbcf65dea3493863a83ca368393e27df5515

test:
  secret_key_base: 042745a7daa50fd8ef63580f421b236fbdcc8f7ebc9c3d81b5cb0b50de4a97078f9d87aef8a62db200a1a8e76f0f068684e7998e59e8f60a8257bb173e455a32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
